[workspace]
resolver = "2"
members = [
    "crates/main",
    "crates/jmap",
    "crates/jmap-proto",
    "crates/imap",
    "crates/imap-proto",
    "crates/smtp",
    "crates/managesieve",
    "crates/nlp",
    "crates/store",
    "crates/directory",
    "crates/utils",
    "crates/maybe-async",
    "crates/cli",
    "crates/install",
    "tests",
]

[profile.dev]
opt-level = 0
debug = 1
codegen-units = 4
lto = false
incremental = true
panic = 'unwind'
debug-assertions = true
overflow-checks = false
rpath = false

[profile.release]
opt-level = 3
debug = false
codegen-units = 1
lto = true
incremental = false
panic = 'unwind'
debug-assertions = false
overflow-checks = false
rpath = false
#strip = true

[profile.test]
opt-level = 0
debug = 1
#codegen-units = 16
lto = false
incremental = true
debug-assertions = true
overflow-checks = true
rpath = false

[profile.bench]
opt-level = 3
debug = false
codegen-units = 1
lto = true
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false

# TODO: remove before merge
[patch."https://github.com/stalwartlabs/mail-send"]
mail-send = { git = "https://github.com/hoxxep/mail-send", rev = "1fcb932" }
